/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('options_table').del()
  await knex('options_table').insert([
    {question_id: 1, option: 'A', detail: 'North Atlantic Treaty Organization'},
    {question_id: 1, option: 'B', detail: 'North America Treaty Organization'},
    {question_id: 1, option: 'C', detail: 'North Atlantic Trust Organization'},
    {question_id: 1, option: 'D', detail: 'North Alliance Treaty Organization'},
    {question_id: 2, option: 'A', detail: 'USA'},
    {question_id: 2, option: 'B', detail: 'CANADA'},
    {question_id: 2, option: 'C', detail: 'NORWAY'},
    {question_id: 2, option: 'D', detail: 'FINLAND'},
    {question_id: 3, option: 'A', detail: 'Vanuatu'},
    {question_id: 3, option: 'B', detail: 'Vatican City'},
    {question_id: 3, option: 'C', detail: 'Luxembourg'},
    {question_id: 3, option: 'D', detail: 'Monaco'},
    {question_id: 4, option: 'A', detail: 'RUSSIA'},
    {question_id: 4, option: 'B', detail: 'CANADA'},
    {question_id: 4, option: 'C', detail: 'USA'},
    {question_id: 4, option: 'D', detail: 'CHINA'},
    {question_id: 5, option: 'A', detail: 'ASMARA'},
    {question_id: 5, option: 'B', detail: 'TALINN'},
    {question_id: 5, option: 'C', detail: 'MALABO'},
    {question_id: 5, option: 'D', detail: 'HELSINKI'},
    {question_id: 6, option: 'A', detail: 'USA'},
    {question_id: 6, option: 'B', detail: 'FRANCE'},
    {question_id: 6, option: 'C', detail: 'NEW ZEALAND'},
    {question_id: 6, option: 'D', detail: 'INDIA'},
    {question_id: 7, option: 'A', detail: 'INDONASIA'},
    {question_id: 7, option: 'B', detail: 'USA'},
    {question_id: 7, option: 'C', detail: 'INDIA'},
    {question_id: 7, option: 'D', detail: 'CHINA'},
    {question_id: 8, option: 'A', detail: 'North Mariana Islands'},
    {question_id: 8, option: 'B', detail: 'Estonia'},
    {question_id: 8, option: 'C', detail: 'Ukraine'},
    {question_id: 8, option: 'D', detail: 'Djibouti'},
    {question_id: 9, option: 'A', detail: 'CHINA'},
    {question_id: 9, option: 'B', detail: 'MALAYASIA'},
    {question_id: 9, option: 'C', detail: 'JAPAN'},
    {question_id: 9, option: 'D', detail: 'KOREA'},
    {question_id: 10, option: 'A', detail: 'QATAR'},
    {question_id: 10, option: 'B', detail: 'LUXEMBOURG'},
    {question_id: 10, option: 'C', detail: 'MACAU'},
    {question_id: 10, option: 'D', detail: 'Liechtenstein'},
    {question_id: 11, option: 'A', detail: 'Compressed Archive file'},
    {question_id: 11, option: 'B', detail: 'Image File'},
    {question_id: 11, option: 'C', detail: 'Temporary File'},
    {question_id: 11, option: 'D', detail: 'Audio File'},
    {question_id: 12, option: 'A', detail: 'Internet'},
    {question_id: 12, option: 'B', detail: 'Intranet'},
    {question_id: 12, option: 'C', detail: 'Local Area Network'},
    {question_id: 12, option: 'D', detail: 'Wide Area Network'},
    {question_id: 13, option: 'A', detail: 'System file'},
    {question_id: 13, option: 'B', detail: 'Animation/movie file'},
    {question_id: 13, option: 'C', detail: 'MS Encarta document'},
    {question_id: 13, option: 'D', detail: 'Image file'},
    {question_id: 14, option: 'A', detail: '1976'},
    {question_id: 14, option: 'B', detail: '1972'},
    {question_id: 14, option: 'C', detail: '1980'},
    {question_id: 14, option: 'D', detail: '1984'},
    {question_id: 15, option: 'A', detail: 'TEXT FILE'},
    {question_id: 15, option: 'B', detail: 'IMAGE FILE'},
    {question_id: 15, option: 'C', detail: 'AUDIO FILE'},
    {question_id: 15, option: 'D', detail: 'Adobe Acrobat file'},
    {question_id: 16, option: 'A', detail: 'LO'},
    {question_id: 16, option: 'B', detail: 'HELLO WORLD'},
    {question_id: 16, option: 'C', detail: 'MARY HAD A LITTLE LAMB'},
    {question_id: 16, option: 'D', detail: 'cyberspace, the final frontier'},
    {question_id: 17, option: 'A', detail: '74 mins'},
    {question_id: 17, option: 'B', detail: '56 mins'},
    {question_id: 17, option: 'C', detail: '60 mins'},
    {question_id: 17, option: 'D', detail: '90 mins'},
    {question_id: 18, option: 'A', detail: 'Digital Transmission Protocol'},
    {question_id: 18, option: 'B', detail: 'Desk-Top Publishing'},
    {question_id: 18, option: 'C', detail: 'Data Type Programming'},
    {question_id: 18, option: 'D', detail: 'Document Type Processing'},
    {question_id: 19, option: 'A', detail: 'Command Description'},
    {question_id: 19, option: 'B', detail: 'Change Data'},
    {question_id: 19, option: 'C', detail: 'Copy Density'},
    {question_id: 19, option: 'D', detail: 'Compact Disc'},
    {question_id: 20, option: 'A', detail: 'Backup file'},
    {question_id: 20, option: 'B', detail: 'Audio file'},
    {question_id: 20, option: 'C', detail: ' Animation/movie file'},
    {question_id: 20, option: 'D', detail: 'MS Encarta document'},
    {question_id: 1, option: 'B', detail: 'Barbarous'},
    {question_id: 21, option: 'A', detail: 'wild'},
    {question_id: 21, option: 'C', detail: 'Brave'},
    {question_id: 21, option: 'D', detail: 'Roving'},
    {question_id: 22, option: 'A', detail: 'Big'},
    {question_id: 22, option: 'B', detail: 'Cut'},
    {question_id: 22, option: 'C', detail: 'Little'},
    {question_id: 22, option: 'D', detail: 'Green'},
    {question_id: 23, option: 'A', detail: 'Impact'},
    {question_id: 23, option: 'B', detail: 'Impress'},
    {question_id: 23, option: 'C', detail: 'Implant'},
    {question_id: 23, option: 'D', detail: 'Implement'},
    {question_id: 24, option: 'A', detail: 'Secure'},
    {question_id: 24, option: 'B', detail: 'Exalted'},
    {question_id: 24, option: 'C', detail: 'Uncertain'},
    {question_id: 24, option: 'D', detail: 'Important'},
    {question_id: 25, option: 'A', detail: 'Abstract'},
    {question_id: 25, option: 'B', detail: 'Unorthodox'},
    {question_id: 25, option: 'C', detail: 'Baffling'},
    {question_id: 25, option: 'D', detail: 'Conservative'},
    {question_id: 26, option: 'A', detail: 'Destitute'},
    {question_id: 26, option: 'B', detail: 'Indolent'},
    {question_id: 26, option: 'C', detail: 'Affluent'},
    {question_id: 26, option: 'D', detail: 'Inane'},
    {question_id: 27, option: 'A', detail: 'Come'},
    {question_id: 27, option: 'B', detail: 'Forward'},
    {question_id: 27, option: 'C', detail: 'Retreat'},
    {question_id: 27, option: 'D', detail: 'Move'},
    {question_id: 28, option: 'A', detail: 'Hostile'},
    {question_id: 28, option: 'B', detail: 'Tacit'},
    {question_id: 28, option: 'C', detail: 'Overt'},
    {question_id: 28, option: 'D', detail: 'Generic'},
    {question_id: 29, option: 'A', detail: 'Grumpy'},
    {question_id: 29, option: 'B', detail: 'Friendly'},
    {question_id: 29, option: 'C', detail: 'Pleasant'},
    {question_id: 29, option: 'D', detail: 'Affable'},
    {question_id: 30, option: 'A', detail: 'Praised'},
    {question_id: 30, option: 'B', detail: 'Supervised'},
    {question_id: 30, option: 'C', detail: 'Reproached'},
    {question_id: 30, option: 'D', detail: 'Detained'},
    {question_id: 31, option: 'A', detail: 'seismograph'},
    {question_id: 31, option: 'B', detail: 'quake meter'},
    {question_id: 31, option: 'C', detail: 'barometer'},
    {question_id: 31, option: 'D', detail: 'none of the above'},
    {question_id: 32, option: 'A', detail: 'Earthquake scale'},
    {question_id: 32, option: 'B', detail: 'Seismic scale'},
    {question_id: 32, option: 'C', detail: 'Richter scale'},
    {question_id: 32, option: 'D', detail: 'Temblor scale'},
    {question_id: 33, option: 'A', detail: 'comma'},
    {question_id: 33, option: 'B', detail: 'origin'},
    {question_id: 33, option: 'C', detail: 'epicenter'},
    {question_id: 33, option: 'D', detail: 'focus'},
    {question_id: 34, option: 'A', detail: 'Strike'},
    {question_id: 34, option: 'B', detail: 'Comma'},
    {question_id: 34, option: 'C', detail: 'Epicenter'},
    {question_id: 34, option: 'D', detail: 'Origin'},
    {question_id: 35, option: 'A', detail: 'P waves'},
    {question_id: 35, option: 'B', detail: 'S waves'},
    {question_id: 35, option: 'C', detail: 'Surface waves'},
    {question_id: 35, option: 'D', detail: 'All of the above'},
    {question_id: 36, option: 'A', detail: 'push-pull'},
    {question_id: 36, option: 'B', detail: 'side-side'},
    {question_id: 36, option: 'C', detail: 'up-down'},
    {question_id: 36, option: 'D', detail: 'none of the above'},
    {question_id: 37, option: 'A', detail: 'crust and core only'},
    {question_id: 37, option: 'B', detail: 'liquids and gases only'},
    {question_id: 37, option: 'C', detail: 'solids, gases, and liquids'},
    {question_id: 37, option: 'D', detail: 'none of the above'},
    {question_id: 38, option: 'A', detail: 'plate boundaries'},
    {question_id: 38, option: 'B', detail: 'plate surface'},
    {question_id: 38, option: 'C', detail: 'ocean beds'},
    {question_id: 38, option: 'D', detail: 'all of the above'},
    {question_id: 39, option: 'A', detail: 'wave'},
    {question_id: 39, option: 'B', detail: 'scale'},
    {question_id: 39, option: 'C', detail: 'unit'},
    {question_id: 39, option: 'D', detail: 'magnitude'},
    {question_id: 40, option: 'A', detail: '2'},
    {question_id: 40, option: 'B', detail: '3'},
    {question_id: 40, option: 'C', detail: '4'},
    {question_id: 40, option: 'D', detail: '5'},
    {question_id: 41, option: 'A', detail: 'angles'},
    {question_id: 41, option: 'B', detail: 'transversal lines'},
    {question_id: 41, option: 'C', detail: 'vertex'},
    {question_id: 41, option: 'D', detail: 'Parallel Lines'},
    {question_id: 42, option: 'A', detail: 'Triangle'},
    {question_id: 42, option: 'B', detail: 'Rectangle'},
    {question_id: 42, option: 'C', detail: 'Hexagon'},
    {question_id: 42, option: 'D', detail: 'Circle'},
    {question_id: 43, option: 'A', detail: 'TANGENT'},
    {question_id: 43, option: 'B', detail: 'SUPPLEMENTARY'},
    {question_id: 43, option: 'C', detail: 'COMPLEMENTARY'},
    {question_id: 43, option: 'D', detail: 'REFLECTIVE'},
    {question_id: 44, option: 'A', detail: 'circumangle'},
    {question_id: 44, option: 'B', detail: 'right angle'},
    {question_id: 44, option: 'C', detail: 'supplementary angle'},
    {question_id: 44, option: 'D', detail: 'complementary angle'},
    {question_id: 45, option: 'A', detail: 'Solution Set'},
    {question_id: 45, option: 'B', detail: 'Null Set'},
    {question_id: 45, option: 'C', detail: 'Complex Set'},
    {question_id: 45, option: 'D', detail: 'subset'},
    {question_id: 46, option: 'A', detail: 'tangent'},
    {question_id: 46, option: 'B', detail: 'chord'},
    {question_id: 46, option: 'C', detail: 'traversal'},
    {question_id: 46, option: 'D', detail: 'intersector'},
    {question_id: 47, option: 'A', detail: '180'},
    {question_id: 47, option: 'B', detail: '240'},
    {question_id: 47, option: 'C', detail: '360'},
    {question_id: 47, option: 'D', detail: 'none of the above'},
    {question_id: 48, option: 'A', detail: '19/9 days'},
    {question_id: 48, option: 'B', detail: '27 days'},
    {question_id: 48, option: 'C', detail: '28/9 days'},
    {question_id: 48, option: 'D', detail: '25/8 days'},
    {question_id: 49, option: 'A', detail: '50%'},
    {question_id: 49, option: 'B', detail: '75%'},
    {question_id: 49, option: 'C', detail: '80%'},
    {question_id: 49, option: 'D', detail: '125%'},
    {question_id: 50, option: 'A', detail: '20%'},
    {question_id: 50, option: 'B', detail: '30%'},
    {question_id: 50, option: 'C', detail: '40%'},
    {question_id: 50, option: 'D', detail: '50%'},
  ]);
};
